SCR_Faction : "{3FA20B01D950D31E}Configs/Factions/Non-Combatant.conf" {
 m_aFriendlyFactionsIds +{
  "183_Able"
  "183_Nightmare"
  "183_Lancer"
  "183_Aviation"
  "183_Taskmaster"
  "183_Posse"
  "183_Train"
 }
}