SCR_Faction : "{3FA20B01D950D31E}Configs/Factions/Non-Combatant.conf" {
 FactionKey "183rd_Press"
 FactionColor 0.392 0.157 0.624 1
 UIInfo SCR_FactionUIInfo "{56B49118D8D0A9C5}" {
  Name "Embedded Journalists"
  Icon "{7BB7AE674BE729CE}UI/Textures/Editor/EditableEntities/Factions/EditableEntity_Faction_CIV.edds"
  m_sNameUpper "EMBEDDED JOURNALISTS"
 }
 "Radio encryption key" "Sandbox"
 m_OutlineFactionColor 0.045 0 0.084 1
 m_NotificationFactionColor 0.517 0.204 0.823 1
 m_NotificationTextFactionColor 0.392 0.157 0.624 1
 m_bIsPlayable 1
 m_sFactionFlag "{7BB7AE674BE729CE}UI/Textures/Editor/EditableEntities/Factions/EditableEntity_Faction_CIV.edds"
 m_FactionFlagMaterial "{E3BB2EF7F600DD28}Assets/Props/Fabric/Flags/Data/Flag_2_3_CIVILIAN.emat"
 m_FactionLabel FACTION_183_PRESS
 m_aFriendlyFactionsIds +{
  "183_Able"
  "183_Nightmare"
  "183_Lancer"
  "183_Aviation"
  "183_CSB"
  "183_Train"
  "183_Guest"
 }
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{607A9A9FE55EDF5F}" : "{D0DD7F45867D6F90}Configs/EntityCatalog/press/InventoryItems_EntityCatalog_PRESS.conf" {
  }
  SCR_EntityCatalogMultiList "{607A9A9FFA54DFE9}" : "{7C53DF3E1349C5B8}Configs/EntityCatalog/CIV/Vehicles_EntityCatalog_CIV.conf" {
  }
  SCR_EntityCatalogMultiList "{61C8ED1193902596}" : "{45152C9ADA59EEEB}Configs/EntityCatalog/CIV/Groups_EntityCatalog_CIV.conf" {
  }
  SCR_EntityCatalogMultiList "{61C8ED1182211903}" : "{361D4401A7A7102A}Configs/EntityCatalog/CIV/WeaponTripod_EntityCatalog_CIV.conf" {
  }
  SCR_EntityCatalogMultiList "{607A9A9FFBDA2F92}" : "{9D7E5804BB2E9B28}Configs/EntityCatalog/CIV/InventoryItems_EntityCatalog_CIV.conf" {
  }
 }
 m_sFactionBackground "{781301447441F404}UI/Textures/DeployMenu/Loadout-BG/Loadout_BG_Civilian.imageset"
 m_FactionHomeTerritoryConfig SCR_FactionHomeTerritoryConfig "{6134C337FF7969DC}" : "{C961C64284CF8023}Configs/Identities/Territories/FactionHomeTerritory_FIA.conf" {
 }
}