SCR_PlaceableEntitiesRegistry {
 m_sAddon "183rdable"
 m_sSourceDirectory "{A317BA3193B77EF5}Prefabs/Characters"
 m_bExposed 1
 m_Prefabs {
  "{A53CE9D62F4AD5C5}Prefabs/Characters/183rd_Able_Medic.et"
  "{443E618AF5511494}Prefabs/Characters/183rd_Able_rifleman.et"
  "{6C37AE056BD1B77E}Prefabs/Characters/183rd_Able_Leader.et"
  "{EBA29A576581B021}Prefabs/Characters/183rd_Able_jfire.et"
 }
}