SCR_PlaceableEntitiesRegistry {
 m_sAddon "183rdable"
 m_sSourceDirectory "{79DD690A0F239399}Prefabs/Systems"
 m_bExposed 1
 m_Prefabs {
  "{9C9736E613CC62D5}Prefabs/Systems/E_SpawnPoint_183rd_able.et"
  "{0B46BB71AA7EC39F}Prefabs/Systems/VehicleService_183rd_able.et"
  "{53B50340EC040F90}Prefabs/Systems/ArsenalBox_183_Able.et"
 }
}