SCR_PlaceableEntitiesRegistry {
 m_sAddon "183rdable"
 m_sSourceDirectory "{F9291FCE0C1F7605}Prefabs/Vehicles"
 m_bExposed 1
 m_Prefabs {
  "{38186F12F27A61C6}Prefabs/Vehicles/Wheeled/M923A1_command_MERDC.et"
  "{B852D03E85D1F66D}Prefabs/Vehicles/Wheeled/JLTV_CROWS_M240.et"
  "{8A9444452D28F5B3}Prefabs/Vehicles/Wheeled/JLTV_CROWS_M240_Woodland.et"
  "{A19889DD96914B75}Prefabs/Vehicles/Wheeled/JLTV_CROWS.et"
  "{2E6481BC1EE9A767}Prefabs/Vehicles/Wheeled/JLTV_CROWS_Woodland.et"
  "{6BBA4A0E747D2215}Prefabs/Vehicles/Wheeled/JLTV_CROWSII_AIM92.et"
  "{A7E72E0E66B73009}Prefabs/Vehicles/Wheeled/JLTV_CROWSII_AIM92_Woodland.et"
  "{9B906EE7402FDA06}Prefabs/Vehicles/Wheeled/JLTV_CROWSII_Javelin.et"
  "{4DB3F284FE895321}Prefabs/Vehicles/Wheeled/JLTV_CROWSII_Javelin_Woodland.et"
  "{49B5C8D1F28E7B7F}Prefabs/Vehicles/Wheeled/JLTV_CROWSII.et"
  "{36BDCC88B17B3BFA}Prefabs/Vehicles/Wheeled/M923A1_command.et"
  "{4E3A86638BFF9FC6}Prefabs/Vehicles/M997_maxi_ambulance_USAF.et"
  "{FD6C3FAC03F8E761}Prefabs/Vehicles/M997_maxi_ambulance_USAF_D.et"
  "{D17CCBF7FE9AAFEC}Prefabs/Vehicles/Wheeled/JLTV_CROWSII_Woodland.et"
 }
}