SCR_EditableEntityCore {
 m_EntityLabels {
  SCR_EditableEntityCoreLabelSettingExtended "{66E30EA7745F3E81}" {
   m_Info SCR_UIInfo "{550EDE93E0A8DB6E}" {
    Name "183rd Able"
    Description "HHS 183rd Able Company 183rd Air Assult"
    Icon "{4A5E5F934DC401AF}Assets/Logos/able.edds"
   }
   m_Order 1
   m_LabelType FACTION_183_ABLE
   m_LabelGroupType FACTION
   m_eBlackListedModes BUILDING
  }
  SCR_EditableEntityCoreLabelSettingExtended "{66E321E6940AE8B0}" {
   m_Info SCR_UIInfo "{66E321E6BC4ACD79}" {
    Name "183rd Nightmare"
    Description "1st PLT 183rd Able Company 183rd Air Assult"
    Icon "{F8D9027845101844}Assets/Logos/nighmare.edds"
   }
   m_Order 1
   m_LabelType FACTION_183_NIGHTMARE
   m_LabelGroupType FACTION
   m_eBlackListedModes BUILDING
  }
  SCR_EditableEntityCoreLabelSettingExtended "{66E321C2718C4033}" {
   m_Info SCR_UIInfo "{66E321E6BC4ACD79}" {
    Name "183_Lancer"
    Description "2nd PLT 183rd Able Company 183rd Air Assult"
    Icon "{30F6D272B8425EE3}Assets/Logos/lancer.edds"
   }
   m_Order 1
   m_LabelType FACTION_183_LANCER
   m_LabelGroupType FACTION
   m_eBlackListedModes BUILDING
  }
  SCR_EditableEntityCoreLabelSettingExtended "{66E321BBF1C71CA5}" {
   m_Info SCR_UIInfo "{66E321E6BC4ACD79}" {
    Name "183_Bravo"
    Description "2-183rd Combat Support Battalion "
    Icon "{30F6D272B8425EE3}Assets/Logos/lancer.edds"
   }
   m_Order 1
   m_LabelType FACTION_183_BRAVO
   m_LabelGroupType FACTION
   m_eBlackListedModes BUILDING
  }
  SCR_EditableEntityCoreLabelSettingExtended "{66E321BC25D2C51A}" {
   m_Info SCR_UIInfo "{66E321E6BC4ACD79}" {
    Name "183_Aviation"
    Description "1-211th Combat Aviation Headquarters"
    Icon "{30F6D272B8425EE3}Assets/Logos/lancer.edds"
   }
   m_Order 1
   m_LabelType FACTION_183_AVAITION
   m_LabelGroupType FACTION
   m_eBlackListedModes BUILDING
  }
 }
}