SCR_MissionHeader {
 World "{7C928EB83311BE1F}Worlds/GM.ent"
 m_sName "Anizay GM for Milsim Units 12 Hour Joint Operation"
 m_sAuthor "Marko Resja"
 m_sDescription "Anizay GM for Milsim Units 12 Hour Joint Operation"
 m_sGameMode "CustomGM"
 m_iPlayerCount 128
}