SCR_EditableEntityCore {
 m_EntityLabels {
  SCR_EditableEntityCoreLabelSetting "{56A8CB478475863D}" {
   m_Info SCR_UIInfo "{56A8CB47AA71E9D9}" {
    Name "HHC 183rd Able Company 1-183rd Air Assault"
    Icon "{4A5E5F934DC401AF}Assets/Logos/able.edds"
   }
   m_Order 1
   m_LabelType FACTION_183_ABLE
   m_LabelGroupType FACTION
  }
  SCR_EditableEntityCoreLabelSetting "{66F3518C0AD1E9E1}" {
   m_Info SCR_UIInfo "{56A8CB47AA71E9D9}" {
    Name "1-211th Combat Aviation "
    Icon "{2A825C261503C22F}Assets/Logos/211.edds"
   }
   m_Order 1
   m_LabelType FACTION_183_AVAITION
   m_LabelGroupType FACTION
  }
  SCR_EditableEntityCoreLabelSetting "{66F402C9DFF720D6}" {
   m_Info SCR_UIInfo "{56A8CB47AA71E9D9}" {
    Name "Nightmare 1st Plt 183rd Able Company 183rd Air Assault"
    Icon "{F8D9027845101844}Assets/Logos/nighmare.edds"
   }
   m_Order 3
   m_LabelType FACTION_183_NIGHTMARE
   m_LabelGroupType FACTION
  }
  SCR_EditableEntityCoreLabelSetting "{66F56052A2E3AC15}" {
   m_Info SCR_UIInfo "{56A8CB47AA71E9D9}" {
    Name "Lancer 2nd Plt 183rd Able Company 183rd Air Assault"
    Icon "{30F6D272B8425EE3}Assets/Logos/lancer.edds"
   }
   m_Order 4
   m_LabelType FACTION_183_LANCER
   m_LabelGroupType FACTION
  }
  SCR_EditableEntityCoreLabelSetting "{66F56052A3EC32B9}" {
   m_Info SCR_UIInfo "{56A8CB47AA71E9D9}" {
    Name "Taskmaster 1st Plt 1-183rd  Bravo Company 183rd Air Assault"
    Icon "{CDA09404A7C1E040}Assets/Logos/csb.edds"
   }
   m_Order 6
   m_LabelType FACTION_183_TASKMASTER
   m_LabelGroupType FACTION
  }
  SCR_EditableEntityCoreLabelSetting "{686ED8309C748EB0}" {
   m_Info SCR_UIInfo "{686ED8309C748EDA}" {
    Name "Posse 2nd Plt 1-183rd  Bravo Company 183rd Air Assault"
    Icon "{CDA09404A7C1E040}Assets/Logos/csb.edds"
   }
   m_Order 6
   m_LabelType FACTION_183_POSSE
   m_LabelGroupType FACTION
  }
  SCR_EditableEntityCoreLabelSetting "{66F56052A4F78283}" {
   m_Info SCR_UIInfo "{56A8CB47AA71E9D9}" {
    Name "Training Detachment  183rd Able Company 183rd Air Assault"
    Icon "{4A5E5F934DC401AF}Assets/Logos/able.edds"
   }
   m_Order 7
   m_LabelType FACTION_183_TRAINING
   m_LabelGroupType FACTION
  }
  SCR_EditableEntityCoreLabelSetting "{6724FCE82445D2B0}" {
   m_Info SCR_UIInfo "{6724FCE82445D238}" {
    Name "Guest 5nd Plt 183rd Able Company 183rd Air Assault"
    Icon "{46FB2FB2C2125A3C}UI/Textures/Flags/US-flag-base-3it.edds"
   }
   m_Order 12
   m_LabelType FACTION_183_GUEST
   m_LabelGroupType FACTION
  }
  SCR_EditableEntityCoreLabelSetting "{684F1D224EFBD617}" {
   m_Info SCR_UIInfo "{684F1D224EFBD6A9}" {
    Name "Embed Journalise"
    Icon "{46FB2FB2C2125A3C}UI/Textures/Flags/US-flag-base-3it.edds"
   }
   m_Order 12
   m_LabelType FACTION_183_PRESS
   m_LabelGroupType FACTION
  }
  SCR_EditableEntityCoreLabelSetting "{684F1D224FD4D952}" {
   m_Info SCR_UIInfo "{684F1D224FD4D9E9}" {
    Name "HHC 183rd Bravo  Company 1-183rd Air Assault"
    Icon "{092DF69A22BDDE00}Assets/Flags/csbflag.edds"
   }
   m_Order 5
   m_LabelType FACTION_183_BRAVO
   m_LabelGroupType FACTION
  }
  SCR_EditableEntityCoreLabelSetting "{684F1D2240903F44}" {
   m_Info SCR_UIInfo "{684F1D2240903F84}" {
    Name "HHS 1-183rd Air Assault"
    Icon "{9822CA02089AD7CF}Assets/Flags/183flag.edds"
   }
   m_Order 1
   m_LabelType FACTION_183_BATT
   m_LabelGroupType FACTION
  }
 }
}