SCR_PlaceableEntitiesRegistry {
 m_sAddon "183rdlancer"
 m_sSourceDirectory "{A317BA3193B77EF5}Prefabs/Characters"
 m_bExposed 1
 m_Prefabs {
  "{CF9C9B457313E897}Prefabs/Characters/183rd_lancer_AT.et"
  "{1AA11C7D065D98B7}Prefabs/Characters/183rd_lancer_grenadier.et"
  "{DDB24915E987FBDE}Prefabs/Characters/183rd_lancer_Leader.et"
  "{904EACB71258ADB6}Prefabs/Characters/183rd_lancer_Medic.et"
  "{45232C9E64D5E228}Prefabs/Characters/183rd_lancer_mg.et"
  "{F940DB5FAB0CB8DA}Prefabs/Characters/183rd_lancer_rifleman.et"
 }
}