SCR_PlaceableEntitiesRegistry {
 m_sAddon "183rdlancer"
 m_sSourceDirectory "{79DD690A0F239399}Prefabs/Systems"
 m_Prefabs {
  "{B2C3DC788CA15F71}Prefabs/Systems/E_SpawnPoint_183rd_lancer.et"
  "{EA364CF5FD0A2C47}Prefabs/Systems/VehicleService_183rd_lancer.et"
  "{DFD6BEE785EA81B8}Prefabs/Systems/ArsenalBox_183_lancer.et"
 }
}