SCR_PlaceableEntitiesRegistry {
 m_sAddon "183rdcustommod"
 m_sSourceDirectory "{79DD690A0F239399}Prefabs/Systems"
 m_bExposed 1
 m_Prefabs {
  "{9C9736E613CC62D5}Prefabs/Systems/able/E_SpawnPoint_183rd_able.et"
  "{65C4EEED439F3C28}Prefabs/Systems/aviation/E_SpawnPoint_183rd_211.et"
  "{5196636D43298B72}Prefabs/Systems/csb/E_SpawnPoint_183rd_csb.et"
  "{B2C3DC788CA15F71}Prefabs/Systems/lancer/E_SpawnPoint_183rd_lancer.et"
  "{A056CDD1038A32A5}Prefabs/Systems/nightmare/E_SpawnPoint_183rd_nightmare.et"
  "{BAF567863815976A}Prefabs/Systems/training/E_SpawnPoint_183rd_train.et"
  "{F68A5DD75E534C63}Prefabs/Systems/guest/E_SpawnPoint_183rd_guest.et"
  "{53B50340EC040F90}Prefabs/Systems/able/ArsenalBox_183_Able.et"
  "{225FEB9E897EE4D3}Prefabs/Systems/aviation/ArsenalBox_183_211.et"
  "{160D661E89C85389}Prefabs/Systems/csb/ArsenalBox_183_csb.et"
  "{1DD9AD7A6586B257}Prefabs/Systems/guest/ArsenalBox_183_guest.et"
  "{DFD6BEE785EA81B8}Prefabs/Systems/lancer/ArsenalBox_183_lancer.et"
  "{710095DC38176840}Prefabs/Systems/nightmare/ArsenalBox_183_nightmare.et"
  "{A87BAE5F8FDFE95C}Prefabs/Systems/training/ArsenalBox_183_train.et"
  "{E1BD10FFA47338E6}Prefabs/Systems/press/ArsenalBox_183_press.et"
  "{0743DAAFA6AB5170}Prefabs/Systems/press/E_SpawnPoint_183rd_press.et"
  "{3D818C873FF22529}Prefabs/Props/Military/AmmoBoxes/AmmoBoxArsenal_Ammunition_183.et"
  "{BA2F9536623E1A47}Prefabs/Systems/batt/ArsenalBox_183_Batt.et"
  "{AA7DC1F0A24245CD}Prefabs/Systems/batt/E_SpawnPoint_183rd_batt.et"
  "{2D60E4912CFC883B}Prefabs/Systems/bravo/ArsenalBox_183_bravo.et"
  "{19095AAEC04287D4}Prefabs/Systems/bravo/E_SpawnPoint_183rd_bravo.et"
 }
}