SCR_PlaceableEntitiesRegistry {
 m_sAddon "183rdcustommod"
 m_sSourceDirectory "{79DD690A0F239399}Prefabs/Systems"
 m_bExposed 1
 m_Prefabs {
  "{9C9736E613CC62D5}Prefabs/Systems/able/E_SpawnPoint_183rd_able.et"
  "{65C4EEED439F3C28}Prefabs/Systems/aviation/E_SpawnPoint_183rd_211.et"
  "{5196636D43298B72}Prefabs/Systems/csb/E_SpawnPoint_183rd_csb.et"
  "{B2C3DC788CA15F71}Prefabs/Systems/lancer/E_SpawnPoint_183rd_lancer.et"
  "{A056CDD1038A32A5}Prefabs/Systems/nightmare/E_SpawnPoint_183rd_nightmare.et"
  "{BAF567863815976A}Prefabs/Systems/training/E_SpawnPoint_183rd_train.et"
  "{53B50340EC040F90}Prefabs/Systems/able/ArsenalBox_183_Able.et"
  "{0B46BB71AA7EC39F}Prefabs/Systems/able/VehicleService_183rd_able.et"
  "{225FEB9E897EE4D3}Prefabs/Systems/aviation/ArsenalBox_183_211.et"
  "{BB474996E6602201}Prefabs/Systems/aviation/VehicleService_183rd_211.et"
  "{3CA65E710B2399E1}Prefabs/Systems/aviation/VehicleServiceAir_183rd_211.et"
  "{DFD6BEE785EA81B8}Prefabs/Systems/lancer/ArsenalBox_183_lancer.et"
  "{EA364CF5FD0A2C47}Prefabs/Systems/lancer/VehicleService_183rd_lancer.et"
  "{160D661E89C85389}Prefabs/Systems/csb/ArsenalBox_183_csb.et"
  "{BB474996E6602202}Prefabs/Systems/csb/VehicleService_183rd_csb.et"
  "{710095DC38176840}Prefabs/Systems/nightmare/ArsenalBox_183_nightmare.et"
  "{D9DEBFDE6207427D}Prefabs/Systems/nightmare/VehicleService_183rd_nightmare.et"
  "{A87BAE5F8FDFE95C}Prefabs/Systems/training/ArsenalBox_183_train.et"
  "{759D2979931B9B22}Prefabs/Systems/training/VehicleService_183rd_train.et"
 }
}