SCR_EntityCatalogMultiList : "{9D7E5804BB2E9B28}Configs/EntityCatalog/CIV/InventoryItems_EntityCatalog_CIV.conf" {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{60E6ED13E10B72D7}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{60E6ED10D3662C19}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogInventoryItem "{60E6ED10D2CAEFAE}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogInventoryItem "{6732E5C235F82927}" {
     m_sEntityPrefab "{8ED5FD32B86DD4CB}Prefabs/Items/Equipment/Binoculars/DSLRCamera/DSLRCamera.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6732E5C235F8297C}" {
       m_eItemType EQUIPMENT
       m_eItemMode SUPPORT_STATION
       m_iSupplyCost 0
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{6732E5C2CEF23BE5}" {
   m_sIdentifier "Vests"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{6732E5C2FB786F7B}" {
     m_sEntityPrefab "{A1E1FA93F395B04F}Prefabs/Vests/Vest_LV119/GRS_LV119_Black_press.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{60E6F4A58230D2F2}" {
       m_eItemType VEST_AND_WAIST
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6732E5C2E6FA4C13}" {
     m_sEntityPrefab "{5061780B35EBB45F}Prefabs/Vests/Custom_Vests/GRS_Custom_Punisher_Black.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6732E5C2E6FA4BA1}" {
       m_eItemType VEST_AND_WAIST
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6732E5C294966252}" {
     m_sEntityPrefab "{5593484A6AECA55E}Prefabs/Pouches/Black/GRS_Front_Large_Medic_Pouch_Black.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{65E6EA42809CB0B7}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6732E5C2965DC740}" {
     m_sEntityPrefab "{6D1286FB1A2BAA0B}Prefabs/Pouches/Black/GRS_Front_Large_Admin_Pouch_Black.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{65E6EA42803AA204}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6732E5C2976017E5}" {
     m_sEntityPrefab "{99EDD92BAB855424}Prefabs/Pouches/Black/GRS_Belly_Trauma_Roll_Black.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{65E6EA42D593AB96}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
      SCR_ArsenalItem "{65E6EA42D593AB95}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
   }
  }
 }
}