SCR_BatchPrefabTemplates {
 m_ComponentsArray {
  SCR_BatchPrefabTemplatesData "{66F313B70D82DE2C}" {
   m_ComponentName "FactionAffiliationComponent"
   m_ComponentAction MODIFY
   m_ComponentAttributesArray {
    SCR_BatchPrefabTemplatesAttributes "{5D6F04ECBA20C15D}" {
     m_AttributeName "faction affiliation"
     m_AttributeValue "183_Able"
    }
   }
  }
  SCR_BatchPrefabTemplatesData "{66F5605103013F9F}" {
   m_ComponentName "FactionAffiliationComponent"
   m_ComponentAction MODIFY
   m_ComponentAttributesArray {
    SCR_BatchPrefabTemplatesAttributes "{5D6F04ECBA20C15D}" {
     m_AttributeName "faction affiliation"
     m_AttributeValue "183_Nightmare"
    }
   }
  }
  SCR_BatchPrefabTemplatesData "{66F560510458BE58}" {
   m_ComponentName "FactionAffiliationComponent"
   m_ComponentAction MODIFY
   m_ComponentAttributesArray {
    SCR_BatchPrefabTemplatesAttributes "{5D6F04ECBA20C15D}" {
     m_AttributeName "faction affiliation"
     m_AttributeValue "183_Lancer"
    }
   }
  }
  SCR_BatchPrefabTemplatesData "{66F5605104EFD844}" {
   m_ComponentName "FactionAffiliationComponent"
   m_ComponentAction MODIFY
   m_ComponentAttributesArray {
    SCR_BatchPrefabTemplatesAttributes "{5D6F04ECBA20C15D}" {
     m_AttributeName "faction affiliation"
     m_AttributeValue "183_Train"
    }
   }
  }
  SCR_BatchPrefabTemplatesData "{66F3518C33A56025}" {
   m_ComponentName "FactionAffiliationComponent"
   m_ComponentAction MODIFY
   m_ComponentAttributesArray {
    SCR_BatchPrefabTemplatesAttributes "{5D6F04ECBA20C15D}" {
     m_AttributeName "faction affiliation"
     m_AttributeValue "183_Aviation"
    }
   }
  }
  SCR_BatchPrefabTemplatesData "{66F402CAEC6B9FE9}" {
   m_ComponentName "FactionAffiliationComponent"
   m_ComponentAction MODIFY
   m_ComponentAttributesArray {
    SCR_BatchPrefabTemplatesAttributes "{5D6F04ECBA20C15D}" {
     m_AttributeName "faction affiliation"
     m_AttributeValue "183_CSB"
    }
   }
  }
  SCR_BatchPrefabTemplatesData "{6724FCE16CCC4B0D}" {
   m_ComponentName "FactionAffiliationComponent"
   m_ComponentAction MODIFY
   m_ComponentAttributesArray {
    SCR_BatchPrefabTemplatesAttributes "{6724FCE16CCC4BDC}" {
     m_AttributeName "faction affiliation"
     m_AttributeValue "183_Guest"
    }
   }
  }
 }
}