EditablePrefabsComponent_EditableEntity {
 m_EntityLabelRules {
  EditablePrefabsLabel_Faction "{56D8B909C631167B}" {
   m_Label FACTION_183_ABLE
   m_FactionToCheck "183_Able"
  }
  EditablePrefabsLabel_Faction "{56D8B909D77CE78B}" {
   m_Label FACTION_183_NIGHTMARE
   m_FactionToCheck "183_Nightmare"
  }
  EditablePrefabsLabel_Faction "{56D8B909D5A71659}" {
   m_Label FACTION_183_LANCER
   m_FactionToCheck "183_Lancer"
  }
  EditablePrefabsLabel_Faction "{66E544919AEE85EE}" {
   m_Label FACTION_183_BRAVO
   m_FactionToCheck "183_Bravo"
  }
  EditablePrefabsLabel_Faction "{66E544919C5AD803}" {
   m_Label FACTION_183_AVAITION
   m_FactionToCheck "183_Aviation"
  }
 }
}