EditablePrefabsComponent_EditableEntity {
 m_EntityLabelRules {
  EditablePrefabsLabel_Faction "{66E30EA066C7BA91}" {
   m_Label FACTION_183_ABLE
   m_FactionToCheck "183rd_ABLE"
  }
  EditablePrefabsLabel_Faction "{66E321E6CF765A8E}" {
   m_Label FACTION_183_NIGHTMARE
   m_FactionToCheck "183_Nightmare"
  }
  EditablePrefabsLabel_Faction "{66E321CDA0AADAB9}" {
   m_Label FACTION_183_LANCER
   m_FactionToCheck "183_Lancer"
  }
  EditablePrefabsLabel_Faction "{66E321BBD1FE7B77}" {
   m_Label FACTION_183_BRAVO
   m_FactionToCheck "183_Bravo"
  }
  EditablePrefabsLabel_Faction "{66E321BC33E7FF1A}" {
   m_Label FACTION_183_AVAITION
   m_FactionToCheck "183_Aviation"
  }
 }
}