SCR_EntityCatalogMultiList : "{8D2FF16F196C73D8}Configs/EntityCatalog/base/Characters_EntityCatalog_Base.conf" {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{66F93869CB5D9D2C}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{66F93869CB5C9E74}" {
     m_sEntityPrefab "{6ED724060255454F}Prefabs/Characters/aviation/183rd_211_medic.et"
    }
    SCR_EntityCatalogEntry "{66F93869CB5F88C2}" {
     m_sEntityPrefab "{7BEF67324B7E7932}Prefabs/Characters/aviation/183rd_211_crew.et"
    }
    SCR_EntityCatalogEntry "{66F93869CB5E7052}" {
     m_sEntityPrefab "{285BBAC23B36A95D}Prefabs/Characters/aviation/183rd_211_pilot.et"
    }
    SCR_EntityCatalogEntry "{66F93869CBA12C07}" {
     m_sEntityPrefab "{07169DABD5A9B454}Prefabs/Characters/aviation/183rd_211_rifleman.et"
    }
   }
  }
 }
}