ACE_SettingsConfig {
 m_aInitialModSettings {
  ACE_Overheating_Settings "{65FA13A496B871DE}" {
   m_fHeatingScale 0.75
   m_fDefaultAirCoolingScale 1.25
   m_fGunpowderAutoignitionTemperature 1200
   m_fMinGlowTemperature 900
  }
 }
}