SCR_PlaceableEntitiesRegistry {
 m_sAddon "183rdTrain"
 m_sSourceDirectory "{A317BA3193B77EF5}Prefabs/Characters"
 m_bExposed 1
 m_Prefabs {
  "{AFC547ECBA7C0806}Prefabs/Characters/183rd_train_AT.et"
  "{08FC0433C7A39043}Prefabs/Characters/183rd_train_grenadier.et"
  "{D8C5E93F1A2AC3EF}Prefabs/Characters/183rd_train_jfire.et"
  "{0456E5C50D1AC727}Prefabs/Characters/183rd_train_Leader.et"
  "{965B9ABE50E1A60B}Prefabs/Characters/183rd_train_Medic.et"
  "{257AF037ADBA02B9}Prefabs/Characters/183rd_train_mg.et"
  "{2FD4967D5D976F83}Prefabs/Characters/183rd_Train_rifleman.et"
 }
}