SCR_PlaceableEntitiesRegistry {
 m_sAddon "183rdTrain"
 m_sSourceDirectory "{79DD690A0F239399}Prefabs/Systems"
 m_Prefabs {
  "{A87BAE5F8FDFE95C}Prefabs/Systems/ArsenalBox_183_train.et"
  "{BAF567863815976A}Prefabs/Systems/E_SpawnPoint_183rd_train.et"
  "{759D2979931B9B22}Prefabs/Systems/VehicleService_183rd_train.et"
 }
}