SCR_EntityCatalogMultiList : "{DA0EA6F7AB8D5A59}Configs/EntityCatalog/base/InventoryItems_EntityCatalog_Base.conf" {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{66F93869CE50BB40}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{670D434D53CFF6BA}" {
     m_sEntityPrefab "{77EF622E4C7DBBFD}Prefabs/Characters/HeadGear/Hat_Boonie_US_01/GL_Hat_Boonie_Black.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6508E36457624718}" {
       m_eItemType HEADWEAR
       m_iSupplyCost 1
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{671415979FDB3C7B}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{67141597982887FA}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{67141597E7CAE994}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{67141597E67507C1}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{67141597E6F38890}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{67141597E53887CC}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{67141597E44B8CA6}" {
     m_bEnabled 0
    }
   }
  }
 }
}