SCR_EditableEntityCore {
 m_EntityLabels {
  SCR_EditableEntityCoreLabelSetting "{66D891D208E8B8BC}" {
   m_Info SCR_UIInfo "{550EDE93E0A8DB6E}" {
    Name "183rd_Able"
    Icon "{25E122ECCFDBD90B}Assets/183logo/able.edds"
   }
   m_Order 1
   m_LabelType FACTION_183_ABLE
   m_LabelGroupType FACTION
  }
 }
}