SCR_MissionHeader {
 World "{7C928EB83311BE1F}Worlds/GM.ent"
 m_sName "183rd Air Assault Nizla GameMaster"
 m_sAuthor "M. Resja"
 m_sDescription "183rd Air Assault Nizla GameMaster"
 m_sGameMode "Custom GM"
 m_iPlayerCount 128
 m_iMapMarkerLimitPerPlayer 50
 m_bIsArmavisionAllowedInMP 1
}