SCR_EntityCatalogMultiList : "{B434695B159CA85F}Configs/EntityCatalog/base/InventoryItems_EntityCatalog_Base.conf" {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{66F93869CE5AEC96}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{6722D7767660FA23}" {
     m_sEntityPrefab "{309D576201C25199}Prefabs/Items/Equipment/Kits/RepairKit_01/EOD_Clippers.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6722D7767660FA76}" {
       m_eItemType HEAL
       m_eItemMode CONSUMABLE
       m_iSupplyCost 5
      }
      SCR_ArsenalItem "{647027E93A40BDC5}" {
       m_eItemType EQUIPMENT
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{671415979FDB3C7B}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{67141597982887FA}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{67141597E7CAE994}" {
     m_bEnabled 0
    }
   }
  }
 }
}