SCR_PlaceableEntitiesRegistry {
 m_Prefabs +{
  "{7A5C4631B7B7DBA4}Prefabs/Compositions/Misc/CustomEntities/InteractionPoints/ArsenalBox_183_Able.et"
  "{1880D4915CE478EE}Prefabs/Compositions/Misc/CustomEntities/InteractionPoints/ArsenalBox_183_Aviation.et"
  "{64737B33E6ADF9E5}Prefabs/Compositions/Misc/CustomEntities/InteractionPoints/ArsenalBox_183_CSB.et"
  "{C8E8969789E8C1A5}Prefabs/Compositions/Misc/CustomEntities/InteractionPoints/ArsenalBox_183_Lancer.et"
  "{33FDC6705B39502F}Prefabs/Compositions/Misc/CustomEntities/InteractionPoints/ArsenalBox_183_Nightmare.et"
 }
}