SCR_EntityCatalogMultiList : "{8D2FF16F196C73D8}Configs/EntityCatalog/base/Characters_EntityCatalog_Base.conf" {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{66F93869CB5D9D2C}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{66F93869CB5C9E74}" {
     m_sEntityPrefab "{680ED2C12B430000}Prefabs/Characters/csb/183rd_csb_medic.et"
    }
    SCR_EntityCatalogEntry "{66F93869CB5E77E2}" {
     m_sEntityPrefab "{85F2B7CCFB3BE276}Prefabs/Characters/csb/183rd_csb_mp.et"
    }
    SCR_EntityCatalogEntry "{66F93869CBA141C3}" {
     m_sEntityPrefab "{89129D73C8D34FB3}Prefabs/Characters/csb/183rd_csb_leader.et"
    }
    SCR_EntityCatalogEntry "{66F93869CBA12C07}" {
     m_sEntityPrefab "{91C1A83B0D0CD956}Prefabs/Characters/csb/183rd_csb_rifleman.et"
    }
    SCR_EntityCatalogEntry "{66F93869CBA1A5A7}" {
     m_sEntityPrefab "{5342F45C7087E13A}Prefabs/Characters/csb/183rd_csb_engineer.et"
    }
   }
  }
 }
}