SCR_PlaceableEntitiesRegistry {
 m_sAddon "183rdcsb"
 m_sSourceDirectory "{A317BA3193B77EF5}Prefabs/Characters"
 m_bExposed 1
 m_Prefabs {
  "{5342F45C7087E13A}Prefabs/Characters/183rd_csb_engineer.et"
  "{89129D73C8D34FB3}Prefabs/Characters/183rd_csb_Leader.et"
  "{680ED2C12B430000}Prefabs/Characters/183rd_csb_Medic.et"
  "{85F2B7CCFB3BE276}Prefabs/Characters/183rd_csb_mp.et"
  "{91C1A83B0D0CD956}Prefabs/Characters/183rd_csb_rifleman.et"
 }
}