SCR_PlaceableEntitiesRegistry {
 m_sAddon "183rdcsb"
 m_sSourceDirectory "{79DD690A0F239399}Prefabs/Systems"
 m_bExposed 1
 m_Prefabs {
  "{5196636D43298B72}Prefabs/Systems/E_SpawnPoint_183rd_csb.et"
  "{BB474996E6602202}Prefabs/Systems/VehicleService_183rd_csb.et"
  "{160D661E89C85389}Prefabs/Systems/ArsenalBox_183_csb.et"
 }
}