SCR_PlaceableEntitiesRegistry {
 m_sAddon "183rdcsb"
 m_sSourceDirectory "{F9291FCE0C1F7605}Prefabs/Vehicles"
 m_bExposed 1
 m_Prefabs {
  "{A19889DD96914B75}Prefabs/Vehicles/Wheeled/JLTV_CROWS.et"
  "{49B5C8D1F28E7B7F}Prefabs/Vehicles/Wheeled/JLTV_CROWSII.et"
  "{D17CCBF7FE9AAFEC}Prefabs/Vehicles/Wheeled/JLTV_CROWSII_Woodland.et"
  "{B852D03E85D1F66D}Prefabs/Vehicles/Wheeled/JLTV_CROWS_M240.et"
  "{8A9444452D28F5B3}Prefabs/Vehicles/Wheeled/JLTV_CROWS_M240_Woodland.et"
  "{2E6481BC1EE9A767}Prefabs/Vehicles/Wheeled/JLTV_CROWS_Woodland.et"
  "{2D74C39A650A3030}Prefabs/Vehicles/Wheeled/M923A1_engineer.et"
  "{37A9871AD4CC9610}Prefabs/Vehicles/Wheeled/M923A1_engineer_MERDC.et"
  "{A042ACE5C2B13206}Prefabs/Vehicles/Wheeled/M923A1_repair.et"
  "{C8656AECF5DF41D9}Prefabs/Vehicles/Wheeled/M923A1_repair_MERDC.et"
  "{2BE1F8B9299B67C1}Prefabs/Vehicles/Wheeled/M923A1_tanker.et"
  "{26013123314183EA}Prefabs/Vehicles/Wheeled/M923A1_tanker_MERDC.et"
  "{F1FBD0972FA5FE09}Prefabs/Vehicles/Wheeled/M923A1_transport.et"
  "{3F2AA823B6C65E1E}Prefabs/Vehicles/Wheeled/M923A1_transport_MERDC.et"
 }
}