SCR_BatchPrefabTemplates {
 m_ComponentsArray {
  SCR_BatchPrefabTemplatesData "{5D6F04ECBA20C161}" {
   m_ComponentName "FactionAffiliationComponent"
   m_ComponentAction MODIFY
   m_ComponentAttributesArray {
    SCR_BatchPrefabTemplatesAttributes "{5D6F04ECBA20C15D}" {
     m_AttributeName "faction affiliation"
     m_AttributeValue "183_Able"
    }
   }
  }
  SCR_BatchPrefabTemplatesData "{5D6F04EC354168D9}" {
   m_ComponentName "FactionAffiliationComponent"
   m_ComponentAction MODIFY
   m_ComponentAttributesArray {
    SCR_BatchPrefabTemplatesAttributes "{5D6F04EC3E2FDFE1}" {
     m_AttributeName "faction affiliation"
     m_AttributeValue "183_Nightmare"
    }
   }
  }
  SCR_BatchPrefabTemplatesData "{66E54492ED149359}" {
   m_ComponentName "FactionAffiliationComponent"
   m_ComponentAction MODIFY
   m_ComponentAttributesArray {
    SCR_BatchPrefabTemplatesAttributes "{5D6F04EC3E2FDFE1}" {
     m_AttributeName "faction affiliation"
     m_AttributeValue "183_Lancer"
    }
   }
  }
  SCR_BatchPrefabTemplatesData "{66E54492975D01A1}" {
   m_ComponentName "FactionAffiliationComponent"
   m_ComponentAction MODIFY
   m_ComponentAttributesArray {
    SCR_BatchPrefabTemplatesAttributes "{5D6F04EC3E2FDFE1}" {
     m_AttributeName "faction affiliation"
     m_AttributeValue "183_Bravo"
    }
   }
  }
  SCR_BatchPrefabTemplatesData "{66E5449297172130}" {
   m_ComponentName "FactionAffiliationComponent"
   m_ComponentAction MODIFY
   m_ComponentAttributesArray {
    SCR_BatchPrefabTemplatesAttributes "{5D6F04EC3E2FDFE1}" {
     m_AttributeName "faction affiliation"
     m_AttributeValue "183_Aviation"
    }
   }
  }
 }
}