SCR_EntityCatalogMultiList : "{8D2FF16F196C73D8}Configs/EntityCatalog/base/Characters_EntityCatalog_Base.conf" {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{66F93869CB5D9D2C}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{66F93869CB5CDB02}" {
     m_sEntityPrefab "{45232C9E64D5E228}Prefabs/Characters/lancer/183rd_lancer_mg.et"
    }
    SCR_EntityCatalogEntry "{66F93869CB5C9E74}" {
     m_sEntityPrefab "{904EACB71258ADB6}Prefabs/Characters/lancer/183rd_lancer_medic.et"
    }
    SCR_EntityCatalogEntry "{66F93869CB5FCC21}" {
     m_sEntityPrefab "{1AA11C7D065D98B7}Prefabs/Characters/lancer/183rd_lancer_grenadier.et"
    }
    SCR_EntityCatalogEntry "{66F93869CB5E77E2}" {
     m_sEntityPrefab "{CF9C9B457313E897}Prefabs/Characters/lancer/183rd_lancer_at.et"
    }
    SCR_EntityCatalogEntry "{66F93869CBA141C3}" {
     m_sEntityPrefab "{DDB24915E987FBDE}Prefabs/Characters/lancer/183rd_lancer_leader.et"
    }
    SCR_EntityCatalogEntry "{66F93869CBA12C07}" {
     m_sEntityPrefab "{F940DB5FAB0CB8DA}Prefabs/Characters/lancer/183rd_lancer_rifleman.et"
    }
   }
  }
 }
}