SCR_EntityCatalogMultiList : "{B434695B159CA85F}Configs/EntityCatalog/base/InventoryItems_EntityCatalog_Base.conf"  {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{671415979FDB3C7B}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{67141597982887FA}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{67141597E7CAE994}" {
     m_bEnabled 0
    }
   }
  }
 }
}
