SCR_PlaceableEntitiesRegistry {
 m_sAddon "183rdnightmare"
 m_sSourceDirectory "{A317BA3193B77EF5}Prefabs/Characters"
 m_bExposed 1
 m_Prefabs {
  "{03C27DA969B2A7F1}Prefabs/Characters/183rd_nightmare_AT.et"
  "{22F26AF44FA84494}Prefabs/Characters/183rd_nightmare_grenadier.et"
  "{2E8C3872DEC10662}Prefabs/Characters/183rd_nightmare_Leader.et"
  "{D12567258B2C6D5C}Prefabs/Characters/183rd_nightmare_Medic.et"
  "{897DCA727E74AD4E}Prefabs/Characters/183rd_nightmare_mg.et"
  "{4D6D0623A7871F10}Prefabs/Characters/183rd_nightmare_rifleman.et"
 }
}