SCR_PlaceableEntitiesRegistry {
 m_sAddon "183rdnightmare"
 m_sSourceDirectory "{79DD690A0F239399}Prefabs/Systems"
 m_Prefabs {
  "{710095DC38176840}Prefabs/Systems/ArsenalBox_183_nightmare.et"
  "{A056CDD1038A32A5}Prefabs/Systems/E_SpawnPoint_183rd_nightmare.et"
  "{D9DEBFDE6207427D}Prefabs/Systems/VehicleService_183rd_nightmare.et"
 }
}