SCR_PlaceableEntitiesRegistry {
 m_sAddon "183rdnightmare"
 m_sSourceDirectory "{F9291FCE0C1F7605}Prefabs/Vehicles"
 m_bExposed 1
 m_Prefabs {
  "{A19889DD96914B75}Prefabs/Vehicles/Wheeled/JLTV_CROWS.et"
  "{49B5C8D1F28E7B7F}Prefabs/Vehicles/Wheeled/JLTV_CROWSII.et"
  "{9B906EE7402FDA06}Prefabs/Vehicles/Wheeled/JLTV_CROWSII_Javelin.et"
  "{4DB3F284FE895321}Prefabs/Vehicles/Wheeled/JLTV_CROWSII_Javelin_Woodland.et"
  "{D17CCBF7FE9AAFEC}Prefabs/Vehicles/Wheeled/JLTV_CROWSII_Woodland.et"
  "{B852D03E85D1F66D}Prefabs/Vehicles/Wheeled/JLTV_CROWS_M240.et"
  "{8A9444452D28F5B3}Prefabs/Vehicles/Wheeled/JLTV_CROWS_M240_Woodland.et"
  "{2E6481BC1EE9A767}Prefabs/Vehicles/Wheeled/JLTV_CROWS_Woodland.et"
 }
}