SCR_MissionHeader {
 World "{0D51025302EF0F11}gamemaster/demo.ent"
 m_sName "Camp Echo"
 m_sAuthor "YonV"
 m_sDescription "183rd Training Map"
 m_sIcon "{F308E32C304B5A30}data/pics/Background.edds"
 m_sLoadingScreen "{10323CBF21DDB2C2}data/pics/ArmA_3_Screenshot_2022.07.31_-_17.57.06.46.edds"
 m_sPreviewImage "{7C78638C00EB1622}data/pics/fury1.edds"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
 m_bIsSavingEnabled 1
}