SCR_MissionHeader {
 World "{5A86ACE7A9C5C6D6}Worlds/gm_ftx_everon_south.ent"
 m_sName "183rd FTX Everon Airfield"
 m_sAuthor "S2"
 m_sDescription "183rd FTX Mission"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 128
}