SCR_PlaceableEntitiesRegistry {
 m_sAddon "183rdCustomMod"
 m_sSourceDirectory "{1A9DB63CE35E3C0B}PrefabsEditable/Auto/Compositions/Misc/CustomEntities/InteractionPoints"
 m_bExposed 1
 m_Prefabs {
  "{8AE03EC6E246054F}PrefabsEditable/Auto/Compositions/Misc/CustomEntities/InteractionPoints/E_ArsenalBox_183_Able.et"
  "{1880D4915CE478EE}Prefabs/Compositions/Misc/CustomEntities/InteractionPoints/ArsenalBox_183_Aviation.et"
  "{64737B33E6ADF9E5}Prefabs/Compositions/Misc/CustomEntities/InteractionPoints/ArsenalBox_183_CSB.et"
  "{C8E8969789E8C1A5}Prefabs/Compositions/Misc/CustomEntities/InteractionPoints/ArsenalBox_183_Lancer.et"
  "{33FDC6705B39502F}Prefabs/Compositions/Misc/CustomEntities/InteractionPoints/ArsenalBox_183_Nightmare.et"
 }
}