SCR_PlaceableEntitiesRegistry {
 m_sAddon "183rdCustomMod"
 m_sSourceDirectory "{3DC0672AC708D7B4}Prefabs/MP/Spawning"
 m_bExposed 1
 m_Prefabs {
  "{871EEC3C74765FDD}Prefabs/MP/Spawning/SpawnPoint_183_Aviation.et"
  "{F694AA569E847C7B}Prefabs/MP/Spawning/SpawnPoint_183rd_ABLE.et"
  "{5F1D5B8ECBB43FBC}Prefabs/MP/Spawning/SpawnPoint_183rd_BRAVO.et"
  "{BEAB05BCDB213F91}Prefabs/MP/Spawning/SpawnPoint_183rd_LANCER.et"
  "{8A9F9FC69CD74920}Prefabs/MP/Spawning/SpawnPoint_183rd_NIGHTMARE.et"
 }
}