SCR_EntityCatalogMultiList {
 m_eEntityCatalogType VEHICLE
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{66F93869D60E6950}" {
   m_sIdentifier "Vehicles"
   m_aEntities {
    SCR_EntityCatalogEntry "{66F93869D60EF074}" {
     m_sEntityPrefab "{5674FAEB9AB7BDD0}Prefabs/Vehicles/Wheeled/M998/M998.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{66F93869D60EF075}" {
      }
     }
    }
    SCR_EntityCatalogEntry "{66F93869D60EF003}" {
     m_sEntityPrefab "{B55C6990A6A9411B}Prefabs/Vehicles/Wheeled/M998/M998_covered.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{66F93869D60EF00C}" {
      }
     }
    }
    SCR_EntityCatalogEntry "{66F93869D60E82C2}" {
     m_sEntityPrefab "{9B1BF9644E0378D6}Prefabs/Vehicles/Wheeled/M998/M998_covered_long.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{66F93869D60E82C5}" {
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{66F93869D61126E3}" {
   m_sIdentifier "Helicopters"
  }
 }
}