SCR_MissionHeader {
 World "{22E9D45193DB2005}Worlds/gm_devtest_campecho.ent"
 m_sName "Dev Test Camp Echo"
 m_sAuthor "YonV"
 m_sDescription "Opps"
 m_sLoadingScreen "{AEAC0A95C72AC0BB}Assets/backgrounds/fury1.edds"
 m_sPreviewImage "{A30FC3399B8A531A}Assets/backgrounds/screen1.edds"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 128
}